apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "adguard-openshift.fullname" . }}-config
  labels:
    {{- include "adguard-openshift.labels" . | nindent 4 }}
data:
  AdGuardHome.yaml: |
    # HTTP Web Interface
    bind_host: "0.0.0.0"
    bind_port: 3000
    
    # DNS Configuration
    dns:
      bind_hosts: ["0.0.0.0"]
      port: 5353
      protection_enabled: true
      filtering_enabled: true
      
      # Upstream DNS Servers (List of strings)
      upstream_dns: 
        - "100.100.1.1"
      
      # Bootstrap DNS Servers (List of strings)
      bootstrap_dns: 
        - "9.9.9.10"
        - "149.112.112.10"
    
    # Logging & TLS
    querylog_enabled: true
    tls:
      enabled: false
    
    # Schema version
    schema_version: 14
